version: 2.1
jobs:
  build:
    # The resource_class feature allows configuring CPU and RAM resources for each job. 
    # Different resource classes are available for different executors. 
    # https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: "large"
    docker:
      - image: cimg/elixir:1.13.0

    environment:
      MIX_ENV: test

    working_directory: /home/circleci/repo
    steps:
      - checkout
      - run:
          name: "Check versions"
          command: |
            mix --version
      - restore_cache:
          keys:
            - elixir-build-v1.13.0-{{ checksum "mix.lock" }}
      - restore_cache:
          keys:
            - elixir-plt-v2-{{ checksum "mix.lock" }}
      - run:
          name: "Install Hex"
          command: mix local.hex --force
      - run:
          name: "Install Rebar"
          command: mix local.rebar --force
      - run:
          name: "Install Elixir dependencies"
          command: mix deps.get
      - run:
          name: "Compile Elixir source"
          command: mix compile --warnings-as-errors
      - save_cache:
          key: elixir-build-v1.13.0-{{ checksum "mix.lock" }}
          paths:
            - "_build"
            - "deps"
            - "~/.mix"
      - run:
          name: "Run Elixir test suite"
          command: mix test --exclude exclude_from_ci
      - run:
          name: "Run Elixir formatter check"
          command: mix format --check-formatted
      - run:
          name: "Run Credo"
          command: mix credo
      - run:
          name: Create PLTs
          command: mix dialyzer --plt
      - save_cache:
          key: elixir-plt-v2-{{ checksum "mix.lock" }}
          paths:
            - "priv/plts"
      - run:
          name: "Run Dialyzer"
          command: mix dialyzer

workflows:
  build:
    jobs:
      - build
